# Generated by Django 5.0.4 on 2025-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0003_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='face_id',
            field=models.ImageField(blank=True, null=True, upload_to='images/profileimage/'),
        ),
    ]
