# Generated by Django 5.0.4 on 2025-09-05 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0004_contact_face_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, message='Entrer moins de 30 caractères'), django.core.validators.MinLengthValidator(2, message='Entrer plus de deux caractères')])),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contactApp.person'),
        ),
    ]
